# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_regtest(self):
    self.driver.get("http://localhost/feane-1.0.0/registration.php")
    self.driver.set_window_size(821, 709)
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("benil basil")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("benil@gmail.com")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("9876543212")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Benil@123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("Benil@123")
    self.driver.find_element(By.ID, "submitBtn").click()
    
    # Add a wait to allow the page to load after form submission
    time.sleep(2)
    
    # Check if we're on a different page (likely login page)
    current_url = self.driver.current_url
    if "login.php" in current_url:
        # We're on the login page, continue with login
        self.driver.find_element(By.ID, "email").send_keys("jimmyjake61@gmail.com")
        self.driver.find_element(By.ID, "password").send_keys("Jake@123")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").click()
        element = self.driver.find_element(By.ID, "email")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("benil@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").click()
        element = self.driver.find_element(By.ID, "password")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "password").send_keys("Benil@123")
        self.driver.find_element(By.ID, "submitBtn").click()
    else:
        # We're still on the registration page or another page
        print(f"Unexpected page after registration: {current_url}")
        # You might want to add additional checks or actions here
  
