# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCart1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cart1(self):
    # Navigate to login page
    self.driver.get("http://localhost/feane-1.0.0/login.php")
    self.driver.set_window_size(823, 711)
    
    # Enter login credentials
    self.driver.find_element(By.ID, "email").send_keys("jimmyjake61@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Jake@123")
    
    # Click login button
    self.driver.find_element(By.ID, "submitBtn").click()
    
    # Wait for login to complete
    time.sleep(2)
    
    # Navigate to menu page directly
    self.driver.get("http://localhost/feane-1.0.0/menu.php")
    
    # Wait for the page to load
    time.sleep(2)
    
    # Add items to cart - using the correct selector
    # First item
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    
    # Wait for the first item to be added
    time.sleep(1)
    
    # Second item - find all add-to-cart buttons and click the second one
    add_to_cart_buttons = self.driver.find_elements(By.CSS_SELECTOR, ".add-to-cart")
    if len(add_to_cart_buttons) > 1:
        add_to_cart_buttons[1].click()
    
    # Wait for the second item to be added
    time.sleep(1)
    
    # Navigate to cart page
    self.driver.get("http://localhost/feane-1.0.0/cart.php")
    
    # Wait for the page to load
    time.sleep(2)
    
    # Verify we're on the cart page
    assert "Your Cart" in self.driver.page_source
  
