# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProfile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_profile(self):
    # First, log in to the application
    self.driver.get("http://localhost/feane-1.0.0/login.php")
    self.driver.set_window_size(823, 711)
    self.driver.find_element(By.ID, "email").send_keys("jimmyjake61@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Jake@123")
    self.driver.find_element(By.ID, "submitBtn").click()
    
    # Wait for login to complete
    time.sleep(2)
    
    # Now navigate directly to the user profile page
    self.driver.get("http://localhost/feane-1.0.0/userprofile.php")
    self.driver.set_window_size(823, 711)
    
    # Wait for the page to load
    time.sleep(2)
    
    # Now proceed with updating the profile
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("jake jimmy")
    self.driver.find_element(By.NAME, "update_profile").click()
  
