# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangepass():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changepass(self):
    # First, log in to the application
    self.driver.get("http://localhost/feane-1.0.0/login.php")
    self.driver.set_window_size(822, 710)
    self.driver.find_element(By.ID, "email").send_keys("benil@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Benil@123")
    self.driver.find_element(By.ID, "submitBtn").click()
    
    # Wait for login to complete
    time.sleep(2)
    
    # Now navigate to the user profile page
    self.driver.get("http://localhost/feane-1.0.0/userprofile.php")
    self.driver.set_window_size(822, 710)
    
    # Wait for the page to load
    time.sleep(2)
    
    # Now proceed with the password change
    self.driver.find_element(By.NAME, "current_password").click()
    self.driver.find_element(By.NAME, "current_password").send_keys("Benil@123")
    self.driver.find_element(By.ID, "new_password").click()
    self.driver.find_element(By.ID, "new_password").send_keys("Benil@1234")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Benil@1234")
    self.driver.find_element(By.ID, "submitBtn").click()
    
    # Wait for the password change to complete
    time.sleep(2)
    
    # Go back to home
    self.driver.find_element(By.LINK_TEXT, "Back to Home").click()
    
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler > span").click()
    self.driver.find_element(By.ID, "userDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    
    # Login with the new password
    self.driver.find_element(By.ID, "email").send_keys("benil@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Benil@1234")
    self.driver.find_element(By.ID, "submitBtn").click()
  
